spring:
  application:
    name: interview-easy-collection-string

logging:  file:    name: /var/tmp/logs/${spring.application.name}/${spring.application.name}
  level:    root: info
    poc.java: debug