spring:
  application:
    name: interview-medium-collection-array

logging:  file:    name: /var/tmp/logs/${spring.application.name}/${spring.application.name}
  level:    root: info
    poc.java: debug